"""
Module for logging in to Xero Blue.

This is the session/auth entry point - NOT a download. Every report/record
module assumes an authenticated session; this module establishes it.

Secret handling (important):
    The caller passes in the email, password, AND a PRE-GENERATED one-time
    passcode (OTP). This module never holds the TOTP secret key and never
    generates a code, so the secret cannot leak from here. The password and the
    OTP are treated as transient and are NEVER written to the logs.

Flow:
    1. Ensure the browser is on the login page (skip if already on a Xero
       Blue / Payroll URL - preserves an existing session).
    2. If already logged in (fast probe), return - nothing to do.
    3. Enter email + password, submit.
    4. If an MFA challenge is shown, enter the provided OTP, tick "Trust this
       device" ONLY if it is not already ticked, and confirm.
    5. Verify the logged-in state; raise if it cannot be confirmed.

There is no retry loop: one OTP in, one attempt. Retrying (with a fresh OTP)
is the caller's concern, since only the caller holds the secret.

Locators live in config.py (the LOGIN_ section). The logged-in check is layered
- the new-UI dashboard <main> first, then the legacy Dashboard link text - so it
survives across UI versions.

ERROR HANDLING: raises typed exceptions from ``iaa_rpa_utils.exceptions`` (login
fails loudly - a caller cannot mistake failure for success):
  - NavigationError - the login form never appeared (could not reach the page)
  - LoginError      - credentials/OTP were entered but the session was not
                      confirmed (e.g. wrong password or wrong/expired OTP)

How to call:
    from login import xero_blue_login

    # Caller generates the OTP from its own held secret and passes the code in:
    xero_blue_login(
        browser,
        email="bot@example.com",
        password=get_credential("xero").password,
        otp=my_totp_provider(),          # 6-digit code, generated by the caller
        xero_blue_url="https://go.xero.com/...",
        payroll_url="https://payroll.xero.com/...",
    )

On success the function returns None. On failure it raises - so a caller need
only wrap the call, not inspect a return value.
"""

from __future__ import annotations

from iaa_rpa_utils import ProcessLogger, setup_logger
from iaa_rpa_utils.exceptions import LoginError, NavigationError

from . import common
from . import config


logger = setup_logger(__name__)


__all__ = ["xero_blue_login"]


# Fast probe for "am I already logged in?" - the elements are either rendered
# now or they are not; we are reading current state, not awaiting navigation.
_LOGGED_IN_PROBE_TIMEOUT = 3
# The post-submit verification DOES wait, since the dashboard loads after submit.
_LOGGED_IN_VERIFY_TIMEOUT = common.EXPORT_TIMEOUT

# One atomic JS statement: tick "Trust this device" ONLY if present and not
# already checked. Reads the live .checked property (an xpath attribute probe
# cannot see a box toggled by script), so it never toggles a trusted device off.
_TRUST_DEVICE_JS = (
    "var cb=document.querySelector(\"[data-automationid='auth-remembermecheckbox--input']\");"
    "if(!cb){return 'absent';}"
    "if(cb.checked){return 'already-checked';}"
    "cb.click();return 'checked';"
)


def xero_blue_login(
    browser,
    *,
    email: str,
    password: str,
    otp: str,
    xero_blue_url: str,
    payroll_url: str,
) -> None:
    """
    Log in to Xero Blue. Returns None on success; raises on failure.

    Args:
        browser:        SeleniumBrowser wrapper.
        email:          Account email.
        password:       Account password (never logged).
        otp:            Pre-generated 6-digit MFA code (never logged). Used only
                        if an MFA challenge is presented.
        xero_blue_url:  Xero Blue login URL.
        payroll_url:    Xero Payroll URL (treated as an already-valid session).

    Raises:
        NavigationError: the login form never appeared.
        LoginError:      the session could not be confirmed after entering
                         credentials/OTP.
    """
    with ProcessLogger("Xero Blue Login", logger):
        logger.info(f"Xero Blue URL: {xero_blue_url}")
        logger.info(f"Payroll URL: {payroll_url}")
        logger.info(f"Email: {email}")   # email only; never password/otp

        logger.info("STEP 1: Ensuring the browser is on the login page...")
        open_login_page(browser, xero_blue_url, payroll_url)

        logger.info("STEP 2: Checking for an existing session...")
        if is_logged_in(browser, timeout=_LOGGED_IN_PROBE_TIMEOUT):
            logger.info("Active Xero session detected - login not required")
            return

        logger.info("STEP 3: Entering credentials...")
        enter_credentials(browser, email, password)

        logger.info("STEP 4: Handling MFA if challenged...")
        handle_mfa_if_present(browser, otp)

        logger.info("STEP 5: Verifying logged-in state...")
        if not is_logged_in(browser, timeout=_LOGGED_IN_VERIFY_TIMEOUT):
            raise LoginError("Login did not complete - dashboard was not reached")
        logger.info("Login confirmed")


def open_login_page(browser, xero_blue_url: str, payroll_url: str) -> None:
    """Navigate to the login page unless already on a Xero Blue / Payroll URL
    (which would mean a session already exists)."""
    current_url = browser.driver.current_url
    logger.info(f"Current URL: {current_url}")
    if xero_blue_url in current_url:
        logger.info("Already on the Xero Blue page - no navigation required")
    elif payroll_url in current_url:
        logger.info("Already on the Xero Payroll page - no navigation required")
    else:
        logger.info("Navigating to the Xero Blue login page...")
        browser.driver.get(xero_blue_url)


def enter_credentials(browser, email: str, password: str) -> None:
    """Enter email + password and submit. If the email field never appears the
    login page did not load - that is a NavigationError."""
    if not browser.does_page_contain_element(config.LOGIN_EMAIL_INPUT, timeout=common.DEFAULT_ELEMENT_TIMEOUT):
        raise NavigationError("Login form did not appear (email field not found)")

    common.clear_and_type(browser, config.LOGIN_EMAIL_INPUT, email)
    logger.info("Email entered")
    common.clear_and_type(browser, config.LOGIN_PASSWORD_INPUT, password)
    logger.info("Password entered")   # value never logged

    browser.click_element(config.LOGIN_SUBMIT_BUTTON, timeout=common.DEFAULT_ELEMENT_TIMEOUT)
    logger.info("Login form submitted")


def handle_mfa_if_present(browser, otp: str) -> None:
    """If an MFA challenge is shown, enter the provided OTP, tick trust-device
    (only if not already ticked), and confirm. If no challenge appears, do
    nothing."""
    if not browser.does_page_contain_element(config.LOGIN_MFA_OTP_INPUT, timeout=common.DEFAULT_ELEMENT_TIMEOUT):
        logger.info("No MFA challenge presented")
        return

    logger.info("MFA challenge detected - entering the provided code...")
    common.clear_and_type(browser, config.LOGIN_MFA_OTP_INPUT, otp)   # code never logged
    logger.info("MFA code entered")

    _tick_trust_device(browser)

    browser.click_element(config.LOGIN_MFA_CONFIRM_BUTTON, timeout=common.DEFAULT_ELEMENT_TIMEOUT)
    logger.info("MFA code submitted")


def _tick_trust_device(browser) -> None:
    """Best-effort: tick "Trust this device" only if it is present and not
    already checked. Never toggles an already-trusted box off; never aborts
    login on failure."""
    try:
        result = browser.execute_javascript(_TRUST_DEVICE_JS)
        if result == "checked":
            logger.info("'Trust this device' ticked")
        elif result == "already-checked":
            logger.info("'Trust this device' was already ticked - left as-is")
        else:
            logger.info("'Trust this device' checkbox not present - skipped")
    except Exception as e:
        logger.info(f"'Trust this device' step skipped (non-fatal): {e}")


def is_logged_in(browser, timeout: int) -> bool:
    """Layered logged-in check: new-UI dashboard <main> first, then the legacy
    Dashboard link. First hit wins."""
    if browser.does_page_contain_element(config.LOGIN_HOME_MAIN, timeout=timeout):
        return True
    if browser.does_page_contain_element(config.LOGIN_DASHBOARD_LINK, timeout=timeout):
        return True
    return False
